name: Go Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22.4

    - name: Check out code
      uses: actions/checkout@v3

    - name: Get dependencies
      run: go mod download

    - name: Run tests
      run: go test ./...